### ISSUE TITLE
Saved history cannot be loaded?

### ISSUE THREAD

**Issue by samthiele** [cgre-aachen/pynoddy#38]
If I create a new noddy model as follows:

```
history = NoddyHistory()
history.add_event('stratigraphy', event_options={'num_layers' : 3,
                                                 'layer_names' : ["top","middle","bottom"],
                                                 'layer_thickness' : [100,200,700]})
history.write_history("model.his")
```

I can save it / execute it / load it in Noddy GUI without issues. 

But.... I can't open it with pynoddy? The following gives me an error:
`his = NoddyHistory("model.his")`

>~/opt/anaconda3/envs/hylite/lib/python3.6/site-packages/pynoddy/events.py in parse_event_lines(self, lines)
>     127         #         self.property_lines[l[0].strip()] = i
>     128 
> --> 129         self.name = self.event_lines[-1].split("=")[1].strip()
>     130 
>     131     def update_properties(self, **kwds):
> 
> IndexError: list index out of range

Any thoughts?

**Comment by samthiele** [comment]
Oh, and this is the generated .his file ==> seems fine to me.
[model.txt](https://github.com/cgre-aachen/pynoddy/files/6102208/model.txt)

**Comment by markjessell** [comment]
Hi Sam
Have you tried saving out the history that you could read in from Noddy and see if that works in  pynoddy. If so you can then do a diff on the two files.
Cheers
Mark

Mark Jessell
Professor/ Western Australian Fellow
Centre for Exploration Targeting/ SES • M006, Perth WA 6009 Australia
T +61 8 6488 5803 • E mark.jessell@uwa.edu.au

________________________________

**Comment by samthiele** [comment]
Good idea - though the differences seem rather trivial to me (see below). I suspect this is more an issue with `pynoddy.events.parse_event_lines( ...  )`. But, I'm curious to see if anyone else can reproduce this, or if I just have something weird going on locally.

<img width="305" alt="Screen Shot 2021-03-08 at 4 29 14 pm" src="https://user-images.githubusercontent.com/10939946/110342209-6ddbc300-802b-11eb-98dd-e7560b962d5f.png">

**Comment by samthiele** [comment]
Gah! There's deffo something funny going on.... I'm getting outputs that have the wrong extent too (tested using .his files generated with the GUI). I can change the cell size, but somehow the extent (calculated via pynoddy) is fixed to (3400.0, 3400.0, 500.0). Maybe I'm just allergic to Macs 😅

`his = NoddyHistory("axes.his")
print(".his extent = ", his.get_extent())
pynoddy.compute_model("axes.his","0_output", sim_type='BLOCK')
model = NoddyOutput("0_output")
print("Output extent = ", (model.xmax - model.xmin, model.ymax - model.ymin, model.zmax - model.zmin))
print("              =  %s %d m blocks" % (model.block.shape,model.delx) )`

> .his extent =  (1000.0, 1000.0, 500.0)
> Output extent =  (3400.0, 3400.0, 500.0)
>               =  (170, 170, 25) 20 m blocks

[axes.txt](https://github.com/cgre-aachen/pynoddy/files/6102622/axes.txt)

**Comment by flohorovicic** [comment]
So, I can open both files that you attached above just fine. Can you send the `model.his` that fails over again?

**Comment by samthiele** [comment]
I figured out the problem with the save/load issue - somehow pynoddy was installing an older version; when I instead installed it with `python setup_without_SALib.py install` then it fixed the issue (I noticed because the version number in the .his files was different to what pynoddy should be writing). 

Still haven't figured out why the noddy executable is building models with incorrect extents though. Could be something strange going on with my setup again... If you run the axes.his file do you get the correct extent? (1000,1000,500)?

**Comment by flohorovicic** [comment]
Thanks, that's an important point - I need to update the pip release! 

Concerning the extent: I get:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/1070677/110736161-769ae780-822b-11eb-9767-f17f56b337fd.png">

**Comment by samthiele** [comment]
Thanks for testing - I guess this must be some strange thing I have going on locally. Will try installing pynoddy from scratch and see if that helps. I guess we can close this issue now 👍

**Comment by samthiele** [comment]
Small update - I managed to get noddy to compute with the correct extents by copying the events and block options (and nothing else) from the .his file (Version = 7.11) exported from the Noddy GUI into a .his file created from scratch using pynoddy (Version = 7.03). 

Doing a diff between the two files (see attached) it seems there are quite a few differences in the GeophysicsOptions - could this be causing the padding to occur somehow? (given I presume Noddy does pad the model when calculating gravity / magnetic forward models? ).

<img width="385" alt="Screen Shot 2021-03-11 at 2 15 10 pm" src="https://user-images.githubusercontent.com/10939946/110792851-32800500-8274-11eb-8f4d-08d9a4f98ba3.png">


[axes_pynoddy.his.txt](https://github.com/cgre-aachen/pynoddy/files/6123185/axes_pynoddy.his.txt)

[axes_noddy.his.txt](https://github.com/cgre-aachen/pynoddy/files/6123183/axes_noddy.his.txt)

**Comment by markjessell** [comment]
Hi yes this is not a bug but a feature....

Noddy uses the geophysics parameters to control the voxel geology output for consistency. If you use Spatial as the geophysics mode it adds padding, if you use spectral it doesn't so, if you want to use spatial and have no padding set the GPSRange to 0 (GPS was my shorthand for geophysics before GPS became a thing!)

cheers

Mark

**Comment by flohorovicic** [comment]
Thanks a lot for clarifying, @markjessell! It was not obvious to me that you were trying a geophysical forward model, @samthiele. But it should still be possible to load the `.his`-file created in Noddy with pynoddy. Does that work now (considering the aspect of extra padding)?

**Comment by samthiele** [comment]
Thanks @markjessell - that it what I suspected was happening. And @flohorovicic  - I'm not trying to run a geophysical forward model, and am running _pynoddy_ in BLOCK mode. I think this is just the "default" setup that is saved when using the Noddy GUI (which must automatically trim the model somehow before displaying it?). 

Maybe we should add something to _pynoddy_ that sets GPSRange to 0 unless `'geophys' in sim_type.lower() or  'all' in sim_type.lower()`? Either that or it automatically trims the padding off the block - I find it counterintuitive that a model built using the GUI gives different results when run in pynoddy.

**Comment by samthiele** [comment]
And @flohorovicic  - yes; other than the padding, I can load and run .his files created using the Noddy GUI without any (other) issues

**Comment by flohorovicic** [comment]
Problem resolved
